### ISSUE TITLE
Can't run AetherShell

### ISSUE THREAD

**Issue by Art10001** [isuretpolos/AetherElements#5]
```
java -jar aether-shell-1.0.1.jar
no main manifest attribute, in aether-shell-1.0.1.jar
```
Please fix.

**Comment by Art10001** [comment]
After having inserted a manifest, it now says:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/beryx/textio/TextIoFactory                                                                       at isuret.polos.aether.shell.AetherShell.<init>(AetherShell.java:32)        at isuret.polos.aether.shell.AetherShell.main(AetherShell.java:28)  Caused by: java.lang.ClassNotFoundException: org.beryx.textio.TextIoFactory         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)               at java.lang.ClassLoader.loadClass(ClassLoader.java:418)                    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)            at java.lang.ClassLoader.loadClass(ClassLoader.java:351)                    ... 2 more`

**Comment by isuretpolos** [comment]
I fixed that by including in the pom.xml the build plugin for a runnable jar with dependencies. It will now also automatically included in the release zip inside the action tab. Thanks for letting me know!
